name: Bot 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 330
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm install

      - name: Run Bot (5.5h)
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: timeout 320m node index.js || true
